### ISSUE TITLE
starship burn

### ISSUE THREAD

**Issue by crazyt0mmy** [Donies1/kOS-Scripts#1]
when I start the program, starship makes a rapid inclination until it reaches 21 km at 0 degrees

![immagine_2024-06-21_174032248](https://github.com/Donies1/kOS-Scripts/assets/173455324/80a4e12a-0b59-4477-9fe3-08c29b36e03b)

**Comment by Donies1** [comment]
What script are you running?

**Comment by Donies1** [comment]
what script are you running?

**Comment by Donies1** [comment]
Updated script, redownload and run "Starship.ks" at launch
